[tool.poetry]
name = "resume"
version = "0.1.0"
description = ""
authors = ["chnnxyz <s@chnn.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
Flask = "^3.0.1"
gunicorn = "^21.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
